### ISSUE TITLE
Reusable functions for connecting with the api

### ISSUE THREAD

**Issue by freefony** [MuhweziDeo/fast-food-fast-challenge4#1]
#### Breakdown
Currently, each module of the app calls a `fetch` function to either post or get data from the api which leads to repeating similar code in many places.

#### Tasks

- [ ] Create a file named `data.js` or `api.js`
- [ ] write your api base URLs as constants
- [ ] write a function named `get` that takes 2 arguments: endpoint, id, and returns the data from that endpoint as and object.
- [ ] write a function named `getAll` that takes an argument, endpoint and returns an array of objects from the api.

#### Requirements
- Create a new branch and make a pull request **Do not merge until told to** 
- Use ES Module to export and import your functions
- Extract repeated codes into utility functions

**Comment by MuhweziDeo** [comment]
I have logged this and going to handle it
